format_version: 3
pipelines:
  simple-go-server-release:
    group: defaultGroup
    template: simple-go-server-1.3
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    secure_variables:
      SECURE: AES:cJAltB5T1RwtyB/hqnZbLA==:8Tlb4ySNTQUZWVhEXJxKzA==
      SECURE1: AES:hK2XdXAShfW8vXeuI97bdA==:cOXCX0aTbg5KdhMl3w3+/g==
    materials:
      git:
        git: https://github.com/bhiravabhatla/simple-go-server.git
        shallow_clone: false
        auto_update: true
        branch: release-1.3
    parameters:
      BRANCH: master-changed
      VERSION: '2.0'
